#!/bin/bash

export ME=$(basename "$0")
cd "$(dirname $0)"

usage() {
    echo "Usage: $ME topic [(-k|--koan) koan_name]"
    exit 1
}

for file in src/*.sh; do
    source "$file"
done

if [[ $# -eq 0 ]]; then
    usage
fi

topic="$1"
shift

# parse options
koan=""
while [[ $# -gt 0 ]]; do
    flag="$1"
    case $flag in
        -k|--koan)
            koan="$2"
            shift
            ;;
        *)
            echo "Unrecognized flag."
            usage
            ;;
    esac
    shift
done

note "Studying $topic."
cd $topic

if [[ -n "$koan" ]]; then
    koans=("$koan")
else
    koans=(*)
fi

for koanfile in "${koans[@]}"; do
    filename=$(basename "$koanfile")
    k="${filename%.*}"
    (./.run $koanfile) &> /dev/null &
    wait %1
    if [[ $? -eq 0 ]]; then
        pass "    Mastered $k."
    else
        fail "    Puzzled by $k."
    fi
done
