#!/bin/bash

export ME=$(basename "$0")
cd "$(dirname $0)"

usage() {
    echo "usage: $ME topic [(-k|--koan) koan_name]"
    exit 1
}

if [[ $# -eq 0 ]]; then
    usage
fi

for file in src/*.sh; do
    source "$file"
done

# parse options
topic="$1"
shift
koan=""
while [[ $# -gt 0 ]]; do
    flag="$1"
    case $flag in
        -k|--koan)
            koan="$2"
            shift
            ;;
        *)
            echo "Unrecognized flag."
            usage
            ;;
    esac
    shift
done

note "${COLOR_BLUE}Studying $topic.${COLOR_RESET}"
cd $topic

if [[ -n "$koan" ]]; then
    koans=("$koan")
else
    koans=(*)
fi

for koanfile in "${koans[@]}"; do
    filename=$(basename "$koanfile")
    k="${filename%.*}"
    result="$(./.run $koanfile 2> /dev/null)"
    if [[ $? -ne 0 ]]; then
        passed=0
        result="?/?"
    else
        passed=$(echo $result | bc)
    fi
    if [[ $passed -eq 1 ]]; then
        out="${COLOR_GREEN}Mastered $k."
    else
        out="${COLOR_RED}Puzzled by $k."
    fi
    len=${#out}
    col=$(($(tput cols)-$len))
    printf '    %s%*s%s\n' "$out" $col "$result" "$COLOR_RESET"
done
